dashboard/urls.py
from turtle import home
from unicodedata import name
from django.contrib import admin
from django.urls import include, path
from users import views
from sso_user.views import sso_register, remove_from_sso
from visitor.views import visitor_registration, add_visitor, edit_visitor, remove_visitor
from booking.views import booking_process, submitted_visitor_report
# from django.contrib.auth import views as auth_views
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.login, name="login"),
    path('change_password/', views.change_password, name="change_password"),
    path('profile/', views.profile, name="profile"),
    path('sso_user_register/', sso_register, name="sso_register"),
    path('sso_remove/<int:id>',remove_from_sso, name="remove_from_sso"),
    path('visitor_registration/',visitor_registration, name="visitor_registration"),
    path('add_visitor/',add_visitor, name="add_visitor"),
    path('edit_visitor/<int:id>',edit_visitor, name="edit_visitor"),
    path('remove_visitor/<int:id>',remove_visitor, name="remove_from_visitor"),
    path('booking_process/',booking_process, name="booking_process"),
    path('submitted_visitor_report/',submitted_visitor_report, name="submitted_visitor_report"),
    path('logout/', views.logout, name="logout"),
    path('reset-password', PasswordResetView.as_view(template_name = "forgot-passwrod.html"), name='password_reset'), 
    path('reset-password/done', PasswordResetDoneView.as_view(template_name = "password-success.html"), name='password_reset_done'), 
    path('reset-password/confirm/<uidb64>[0-9A-Za-z]+)-<token>/', PasswordResetConfirmView.as_view(template_name = "change-password.html"), name='password_reset_confirm'), 
    path('reset-password/complete/', PasswordResetCompleteView.as_view(template_name = "password_reset_done.html"), name='password_reset_complete'),
    
    # path('forgot_password/', auth_views.PasswordResetView.as_view(template_name = "forgot-passwrod.html"), name ='reset_password'),
    # path('password_success/', auth_views.PasswordResetDoneView.as_view(template_name = "password-success.html"), name ='password_reset_done'),
    # path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name = "change-password.html"), name ='password_reset_confirm'),
    # path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name = "password_reset_done.html"), name ='password_reset_complete')
    # path('users/password_reset/', auth_views.PasswordResetView.as_view(
    #     template_name='users/password_reset.html',
    #     email_template_name='users/password_reset_email.html',
    #     subject_template_name='users/password_reset_subject.txt',
    #     success_url='/users/password_reset/done/'),
    #     name='password_reset'
    # ),
    # path('users/password_reset/done/', auth_views.PasswordResetDoneView.as_view(
    #     template_name='users/password_reset_done.html'),
    #     name='password_reset_done'
    # ),
    # path('users/reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
    #     template_name='users/password_reset_confirm.html',
    #     success_url='/users/reset/done/'),
    #     name='password_reset_confirm'
    # ),
    # path('users/reset/done/', auth_views.PasswordResetCompleteView.as_view(
    #     template_name='users/password_reset_complete.html'),
    #     name='password_reset_complete'
    # ),
]

    

users/urls.py
from django.urls import path, include
from .views import login #logout, profile, 

urlpatterns=[
    # path('profile', profile, name='profile'),
    # path('logout$', logout, name='logout'),
    path('login', login, name='login'),
]

visitor/models.py
from random import choice, choices
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model


PROTECTED_AREA= [
    ('Select', 'Select'),
    ('Ranthambore National Park - Sawai Madhopur', 'Ranthambore National Park - Sawai Madhopur'),
    ]
ZONE= [
    ('Select', 'Select'),
    ('Zone 1', 'Zone 1'),
    ('Zone 2', 'Zone 2'),
    ('Zone 3', 'Zone 3'),
    ('Zone 4', 'Zone 4'),
    ('Zone 5', 'Zone 5'),
    ('Zone 6', 'Zone 6'),
    ('Zone 7', 'Zone 7'),
    ('Zone 8', 'Zone 8'),
    ('Zone 9', 'Zone 9'),
    ('Zone 10', 'Zone 10'),
    ]
SHIFT= [
        ('Select', 'Select'),
        ('Morning', 'Morning'),
        ('Evening', 'Evening'),
    ]
VEHICHLE= [
    ('Select', 'Select'),
    ('Canter', 'Canter'),
    ('Gypsy', 'Gypsy'),
]
GENDER= [
    ('Select', 'Select'),
    ('Male', 'Male  '),
    ('Female', 'Female'),
    ('Transgender', 'Transgender'),
]
NATIONALITY= [
    ('Select', 'Select'),
    ('Indian', 'Indian'),
    ('Foreigner', 'Foreigner'),
]
ID_TYPE= [
    ('Select', 'Select'),
    ('Passport', 'Passport'),
    ('Aadhar', 'Aadhar'),
    ('Driving Licence', 'Driving Licence'),
    ('Voter Id', 'Voter Id'),
    ('PAN Card', 'PAN Card'),
    ('Office ID', 'Office ID'),
    ('Student ID', 'Student ID'),
]

class Visitor_Register(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE,)
    protected_area = models.CharField(max_length=100, choices=PROTECTED_AREA, default="Select")
    zone = models.CharField(max_length=10, choices=ZONE, default="Select")
    visit_date = models.DateField()
    choose_shift = models.CharField(max_length=20,choices=SHIFT, default="Select")
    vehicle_type = models.CharField(max_length=20,choices=VEHICHLE, default="Select")
    member_name = models.CharField(max_length=30)
    gender = models.CharField(max_length=30, choices=GENDER, default="Select")
    nationality = models.CharField(max_length=30, choices=NATIONALITY, default="Select")
    id_type = models.CharField(max_length=30, choices=ID_TYPE, default="Select")
    id_number = models.CharField(max_length=30)
    video_cam = models.CharField(max_length=30)
    created_date = models.DateTimeField(auto_now_add=True)

templates/add-visitor.html
{% include 'header.html' %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

            <div class="content-wrapper">
                <h4 class="mainHeading"><a href="/visitor_registration/"><i class="fi fi-rs-arrow-small-left"></i></a>Visitor Registration</h4>
                <div class="formBlock">
                    <div class="row">
                        <div class="col-sm-8 col-md-6 col-lg-4">
                            <form method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label>Select Protected Area</label>
                                    {{ form.protected_area }}
                                </div>
                                <div class="form-group">
                                    <label>Select Zone</label>
                                    {{form.zone}}
                                </div>
                                <div class="form-group">
                                    <label>Date of Visit</label>
                                    {{form.visit_date}}
                                </div>
                                <div class="form-group">
                                    <label>Choose Shift</label>
                                    {{form.choose_shift}}
                                </div>
                                <div class="form-group">
                                    <label>Select Vehicle</label>
                                    {{form.vehicle_type}}
                                </div>
                                <div class="form-group">
                                    <label>Member Name</label>
                                    {{form.member_name}}
                                </div>
                                <div class="form-group">
                                    <label>Gender</label>
                                    {{form.gender}}
                                </div>
                                <div class="form-group">
                                    <label>Nationality</label>
                                    {{form.nationality}}
                                </div>
                                <div class="form-group">
                                    <label>ID Type</label>
                                    {{form.id_type}}
                                </div>
                                <div class="form-group">
                                    <label>ID Number</label>
                                    {{form.id_number}}
                                </div>
                                <div class="form-group">
                                    <label>Video Camera (No.)</label>
                                    {{form.video_cam}}
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="btn themeBtn mt-3">Save</button>
                                </div>
                            </form>
                        </div>
                    </div>
                    
                </div>

            </div>
        </div>
    </div>
    <script>
        $("#id_protected_area").addClass("form-control");
        $("#id_zone").addClass("form-control");
        $("#id_choose_shift").addClass("form-control");
        $("#id_vehicle_type").addClass("form-control");
        $("#id_gender").addClass("form-control");
        $("#id_nationality").addClass("form-control");
        $("#id_id_type").addClass("form-control");
        $("input").addClass("form-control");
    </script>


{% include 'footer.html' %}

templates/change-password.html
{% include 'header.html' %}
            <div class="content-wrapper">
                <h4 class="mainHeading">Change Password</h4>
                <div class="formBlock">
                    <div class="row">
                        <div class="col-sm-8 col-md-6 col-lg-4">
                            <form method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <div class="form-group">
                                    <button type="submit" class="btn themeBtn">Save</button>
                                </div>
                            </form>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>


{% include 'footer.html' %}

templates/footer.html
<script src="/static/js/jquery-3.5.1.slim.min.js"></script>
<script src="/static/js/bootstrap.bundle.min.js"></script>
<script src="/static/js/custom.js"></script>
</body>

</html>

templates/forgot-passwrod.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Wildlife</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/uicons-regular-straight.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/css/responsive.css">


</head>

<body>

    <section class="screenLogin">
        <div class="rightPart flex-column">
            <h2 class="text-dark">Client Logo</h2>
            <!-- <img src="images/logo.svg" width="200px" alt="logo"> -->
            <div class="midBlock mt-3">
                <h3><a class="backBtn" href="/"><i class="fi fi-rs-arrow-small-left"></i></a> Forgot Your Password?</h3>
                <p>Enter the email associated with your VertexPlus account and we'll send an email to reset password</p>
                <form action="" method="post">
                    <div style="display:none">
                        <input type="hidden" value="{{ csrf_token }}" name="csrfmiddlewaretoken">
                    </div>
                    {{ form.email.errors }}
                    <div class="form-group">
                        <label>Email Address</label>
                        {{form}}
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn themeBtn w-100">Send Instructions</button>
                    </div>
                </form>
            </div>
        </div>

    </section>

    <script src="/static/js/jquery-3.5.1.slim.min.js"></script>
    <script src="/static/js/bootstrap.bundle.min.js"></script>
    <script src="/static/js/custom.js"></script>
</body>

</html>

templates/header.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Wildlife</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/uicons-regular-straight.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/css/responsive.css">
    


</head>

<body>
    <div class="wrapper">
        <nav id="sidebar">
            <div class="sidebar-header">
                <h3 class="mb-0">Client Logo</h3>
            </div>
            <ul class="menu">
                <li><a href="/sso_user_register/">SSO User Registration</a></li>
                <li><a href="/visitor_registration/">Visitor Registration</a></li>
                <li><a href="/booking_process/">Booking Process</a></li>
                <li><a href="/submitted_visitor_report/">Submitted Visitor Report</a></li>
            </ul>
        </nav>
        <div class="content">
            <nav class="navbar ">
                <button type="button" id="sidebarCollapse" class="btn btnToogle"> <i class="fi fi-rs-menu-burger"></i></button>
                <div class="btn-group">
                    <button type="button" class="btn btnUser" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <div class="userImg"><img src="/static/images/userImg.png" alt="img"></div>
            Welcome {{request.user}} <i class="fi fi-rs-angle-small-down"></i>
          </button>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a href="{% url 'change_password' %}"><img src="/static/images/key.svg" alt="img"> Change Password</a>
                        <a href="{% url 'logout' %}"><img src="/static/images/logout.svg" alt="img"> Logout</a>
                    </div>
                </div>
            </nav>

templates/login.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Wildlife</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/uicons-regular-straight.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/css/responsive.css">


</head>

<body>

    <section class="screenLogin">
        <div class="rightPart flex-column">
            <h2 class="text-dark">Client Logo</h2>
            <!-- <img src="images/logo.svg" width="200px" alt="logo"> -->
            <div class="midBlock mt-3">
                <h3>Admin Login</h3>
                {% if next %}
                    <form role="form" method="post" action="{% url 'login' %}?next={{ next }}">
                {% else %}
                    <form role="form" method="post" action="{% url 'login' %}">
                {% endif %}
                {% csrf_token %}
                    <div class="form-group">
                        <label>Email Address</label>
                        {{form.username_or_email}}
                    </div>
                    <div class="form-group mb-1">
                        <label>Password</label>
                        {{form.password}}
                        <a href="javascript:void(0);" class="showText">Show</a>
                    </div>
                    <div class="form-group text-right">
                        <a href="reset-password" class="linktext">Forgot your password?</a>
                    </div>
                    <button type="submit" class="btn themeBtn w-100">login</button>
                </form>
            </div>
        </div>

    </section>

    <script src="/static/js/jquery-3.5.1.slim.min.js"></script>
    <script src="/static/js/bootstrap.bundle.min.js"></script>
    <script src="/static/js/custom.js"></script>
</body>

</html>

templates/password-success.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Wildlife</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/uicons-regular-straight.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/css/responsive.css">


</head>

<body>

    <section class="screenLogin">
        <div class="rightPart flex-column">
            <div class="midBlock mt-3">
                <h3>Check your email</h3>
                <p>We have sent new password to your registered email.</p>
                <form>
                    <a href="/" class="btn themeBtn w-100">Ok</a>
                </form>
            </div>
        </div>

    </section>

    <script src="/static/js/jquery-3.5.1.slim.min.js"></script>
    <script src="/static/js/bootstrap.bundle.min.js"></script>
    <script src="/static/js/custom.js"></script>
</body>

</html>

templates/password_reset_done.html
<div class="text-center" style="width: 80%; margin: 0 auto">
    <h1>Password reset complete</h1>
    <h6 style="width: 60%; margin: 0 auto">
      Your Password has been set. You may go ahead and login
    </h6>
  </div>
  <br />
  <div class="text-center">
<a href="{% url 'login' %}">Login</a>
</div>

templates/sso-registration.html
{% include 'header.html' %}

            <div class="content-wrapper">
                <h4 class="mainHeading">SSO User Registration</h4>
                <div class="formBlock">
                    <div class="row">
                        <div class="col-sm-8 col-md-6 col-lg-4">
                            <form method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label>SSO Id</label>
                                    {{form.sso_id}}
                                </div>
                                <div class="form-group">
                                    <label>Password</label>
                                    {{form.password}}
                                </div>
                                <div class="form-group">
                                    <button type="submit" class="btn themeBtn">Save</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="table-responsive-lg">
                    <table class="table">
                        <thead class="thead-light">
                            <tr>
                                <th>S.No.</th>
                                <th>SSO ID</th>
                                <th>Password</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for sso_li in sso_list %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{sso_li.sso_id}}</td>
                                <td>{{sso_li.password}}</td>
                                <td><a class="actionBtn actionBtn2" href="{% url 'remove_from_sso' sso_li.id %}"><i class="fi fi-rs-trash"></i></a></td>
                            </tr>
                            {% endfor %}
                          
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>


{% include 'footer.html' %}

templates/submitted-visitor-report.html
{% include 'header.html' %}

            <div class="content-wrapper">
                <h4 class="mainHeading">Submitted Visitor Report</h4>

                <div class="table-responsive-lg">
                    <table class="table">
                        <thead class="thead-light">
                            <tr>
                                <th>S.No.</th>
                                <th>Member Name</th>
                                <th>Gender</th>
                                <th>Nationality</th>
                                <th>ID Type</th>
                                <th>ID Number</th>
                                <th>Date of Visit</th>
                                <th>Shift</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for data in data_obj %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{data.member_name}}</td>
                                <td>{{data.gender}}</td>
                                <td>{{data.nationality}}</td>
                                <td>{{data.id_type}}</td>
                                <td>{{data.id_number}}</td>
                                <td>{{data.visit_date}}</td>
                                <td>{{data.choose_shift}}</td>
                                <td><a class="actionBtn" href="javascript:void(0);">Rebook</a></td>
                            </tr>
                            {% endfor %}
                            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>


{% include 'footer.html' %}

templates/visitor-registration.html
{% include 'header.html' %}
      
            <div class="content-wrapper">
                <h4 class="mainHeading justify-content-between">Visitor Registration <a class="addBtn" href="/add_visitor/"><i class="fi fi-rs-plus-small"></i></a></h4>
                <div class="table-responsive-lg">
                    <table class="table">
                        <thead class="thead-light">
                            <tr>
                                <th>S.No.</th>
                                <th>Protected Area</th>
                                <th>Zone</th>
                                <th>Date of Visit</th>
                                <th>Shift</th>
                                <th>Vehicle</th>
                                <th>Member Name</th>
                                <th>Gender</th>
                                <th>Nationality</th>
                                <th>ID Type</th>
                                <th>ID Number</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for visit in visits %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{visit.protected_area}}</td>
                                <td>{{visit.zone}}</td>
                                <td>{{visit.visit_date}}</td>
                                <td>{{visit.choose_shift}}</td>
                                <td>{{visit.vehicle_type}}</td>
                                <td>{{visit.member_name}}</td>
                                <td>{{visit.gender}}</td>
                                <td>{{visit.nationality}}</td>
                                <td>{{visit.id_type}}</td>
                                <td>{{visit.id_number}}</td>
                                <td>
                                    <a class="actionBtn mr-2" href="{% url 'edit_visitor' visit.id %}"><img src="/static/images/edit.svg" alt="img"></a>
                                    <a class="actionBtn actionBtn2" href="{% url 'remove_from_visitor' visit.id %}"><i class="fi fi-rs-trash"></i></a>
                                </td>
                            </tr>
                            {% endfor %}
                            
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>



    {% include 'footer.html' %}